# Generated by Django 6.0 on 2026-01-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_by', models.CharField(max_length=100)),
                ('send_type', models.CharField(choices=[('mobile', 'Mobile'), ('email', 'Email')], max_length=10)),
                ('send_for', models.CharField(choices=[('verification', 'Verification'), ('forgot', 'Forgot Password')], max_length=20)),
                ('otp', models.IntegerField()),
                ('created_at', models.IntegerField()),
            ],
        ),
    ]
